### ISSUE TITLE
App-Class-Path is not glob-able on Windows

### ISSUE THREAD

**Issue by mikehearn** [puniverse/capsule#109]
Apparently (second hand reporting here), capsule requires class path elements to be a `Path` and on Windows, a `Path` cannot contain a glob character. The docs however say that App-Class-Path can be used with globs.

**Comment by pron** [comment]
All globbing is (or should be) done internally by Capsule AFAIR. Is there an actual issue to report or just speculation? :)

**Comment by mikehearn** [comment]
The issue that originated this report was "it doesn't work" so I guess so. I will ask for a reduction.

**Comment by mikehearn** [comment]
OK, false alarm, sorry. Communication issue on our side. The actual issue we hit was that we wanted a plugins directory where you could drop JARs that'd be added to the directory, but Capsule checks (not unreasonably) that App-Class-Path entries are actually inside the capsule. Apparently we can do it by writing a custom caplet instead.

**Comment by pron** [comment]
That's right. Capsule ensures that it is self-contained by design, and only allows to deviate from that behavior in custom caplets (that should, ideally, also ensure some form of containment, but that is up to you). Consider using the [Maven caplet](https://github.com/puniverse/capsule-maven) if you want to share dependencies among capsule.
